site_name: Pinterest
pages:
  - Home: index.md
  - Pré-rastreabilidade:
    - RichPicture: rich_picture.md
    - Argumentação: argumentacao.md
  - Elicitação de Requisitos:
    - Storytelling: storytelling.md
    - Análise de Processo: analise_processo.md
    - Introspecção: introspeccao.md
  - Anexos: anexos.md
theme: readthedocs