site_name: Pinterest
extra_css: [extra.css]
pages:
  - HOME: index.md
  - PRÉ-RASTREABILIDADE:
    - Argumentação: argumentacao.md
    - RichPicture: rich_picture.md
  - ELICITAÇÃO DE REQUISITOS:
    - Análise de Discurso: analise_discurso.md
    - Análise de Protocolo: analise_protocolo.md
    - Entrevista: entrevista.md
    - Introspecção: introspeccao.md
    - Questionário: questionario.md
    - Storytelling: storytelling.md
    - Conclusão: conclusao_elicitacao.md
  - MODELAGEM:
    - Cenários: cenarios.md
    - Léxicos: lexicos.md
    - Diagramas de Caso de Uso: diagramas_caso_uso.md
    - Especificações de Caso de Uso: especificacoes_caso_uso.md
    - Backlog do Produto: backlog.md
    - NFR: nfr.md
    - i*: iStar.md
  - ANÁLISE:
    - NFR: analise_NFR.md
    - Pré-rastreabilidade: pre_rastreabilidade_analise.md
    - iStar: Istar_analise_inspecao.md
    - Caso de Uso: inspecao_caso_uso.md
  - PÓS-RASTREABILIDADE:
    - Backward-From: backward_from.md
    - Forward-From: forward_from.md
theme: readthedocs
